# Generated by Django 6.0.6 on 2026-06-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('detection_type', models.CharField(choices=[('face', 'Rostros'), ('mask', 'Mascarillas'), ('helmet', 'Cascos'), ('phone', 'Celulares'), ('body', 'Cuerpo Completo')], default='face', max_length=50)),
                ('total_detections', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sesión de Detección',
                'verbose_name_plural': 'Sesiones de Detección',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_detections', models.PositiveIntegerField(default=0)),
                ('most_detected', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': 'Estadísticas',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('object_label', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('bbox_x', models.IntegerField(default=0)),
                ('bbox_y', models.IntegerField(default=0)),
                ('bbox_w', models.IntegerField(default=0)),
                ('bbox_h', models.IntegerField(default=0)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='captures/')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='detector.detectionsession')),
            ],
            options={
                'verbose_name': 'Evento de Detección',
                'verbose_name_plural': 'Eventos de Detección',
                'ordering': ['-detected_at'],
            },
        ),
    ]
